repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: flake8
        additional_dependencies: [flake8==3.9.2]
