# Generated by Django 5.0.4 on 2024-04-08 23:07
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('yetki', models.CharField(choices=[
                 ('admin', 'Admin'), ('standart', 'Standart')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SorgulamaGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('sorgulama_zamani', models.DateTimeField(auto_now_add=True)),
                ('ip_adresi', models.CharField(max_length=255)),
                ('sonuc', models.TextField()),
                ('sure', models.IntegerField()),
                ('durum', models.CharField(max_length=255)),
                ('kullanici', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='weather.kullanici')),
                ('lokasyon', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='weather.lokasyon')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menupermission',
            name='menu',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuPermission',
        ),
    ]
