# Generated by Django 5.0.4 on 2024-04-09 10:53
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_location_user_remove_sorgulamagecmisi_kullanici_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
