# Generated by Django 5.0.4 on 2024-04-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_weatherdata_delete_queryhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='recorded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='location',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='condition_text',
            field=models.CharField(max_length=100),
        ),
    ]
