# Generated by Django 5.0.4 on 2024-04-09 20:56
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_rename_recorded_at_weatherdata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='request_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
