# Generated by Django 5.0.4 on 2024-04-14 08:01
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_weatherdata_location_name_alter_requestlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='location',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
    ]
