# Generated by Django 5.0.4 on 2024-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_remove_weatherdata_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAPIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('temperature_celsius', models.FloatField()),
                ('temperature_fahrenheit', models.FloatField()),
                ('condition_text', models.CharField(max_length=100)),
            ],
        ),
    ]
