# Generated by Django 5.0.4 on 2024-04-14 08:36
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_weatherapiresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='location',
        ),
    ]
