# Generated by Django 5.0.4 on 2024-04-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_remove_weatherdata_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherAPIResponse',
        ),
    ]
