# Generated by Django 5.0.4 on 2024-04-14 13:55
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_location_user_delete_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),

    ]
