# Generated by Django 5.0.4 on 2024-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_remove_location_user_weatherdata_location_name'),
    ]

    operations = [

        migrations.AddField(
            model_name='weatherdata',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
